set_manual_ventilation:
  name: fals22.services.set_manual_ventilation.name
  description: fals22.services.set_manual_ventilation.description
  fields:
    duration:
      name: fals22.services.set_manual_ventilation.fields.duration.name
      description: fals22.services.set_manual_ventilation.fields.duration.description
      required: true
      selector:
        number:
          min: 0
          max: 300
          unit_of_measurement: "min"
    turn_on:
      name: fals22.services.set_manual_ventilation.fields.turn_on.name
      description: fals22.services.set_manual_ventilation.fields.turn_on.description
      required: true
      selector:
        boolean:

update_multiple_settings:
  name: fals22.services.update_multiple_settings.name
  description: fals22.services.update_multiple_settings.description
  fields:
    min_temp:
      name: fals22.services.update_multiple_settings.fields.min_temp.name
      description: fals22.services.update_multiple_settings.fields.min_temp.description
      selector:
        number:
          min: 0
          max: 35
          unit_of_measurement: "°C"
    max_temp:
      name: fals22.services.update_multiple_settings.fields.max_temp.name
      description: fals22.services.update_multiple_settings.fields.max_temp.description
      selector:
        number:
          min: 0
          max: 40
          unit_of_measurement: "°C"
    ventilation:
      name: fals22.services.update_multiple_settings.fields.ventilation.name
      description: fals22.services.update_multiple_settings.fields.ventilation.description
      selector:
        number:
          min: 0
          max: 99
          unit_of_measurement: "min"
    break:
      name: fals22.services.update_multiple_settings.fields.break.name
      description: fals22.services.update_multiple_settings.fields.break.description
      selector:
        number:
          min: 0
          max: 90
          unit_of_measurement: "min"
    min_hum:
      name: fals22.services.update_multiple_settings.fields.min_hum.name
      description: fals22.services.update_multiple_settings.fields.min_hum.description
      selector:
        number:
          min: 10
          max: 90
          unit_of_measurement: "%"
    difference:
      name: fals22.services.update_multiple_settings.fields.difference.name
      description: fals22.services.update_multiple_settings.fields.difference.description
      selector:
        number:
          min: 0.0
          max: 5.0
          step: 0.1
          unit_of_measurement: "g/m³"